travis:
  secure:
    BINSTAR_TOKEN: e7mLhiVOJi5DCsGsL115CYppsbx0+7iHyrWjkKcD6yZ0B2oyD1NIrjmn5c5kWiwyNFkfRR3/quy1AJfyxtDQdA/r0B6yQFbHyO86dRAbcUDfxPJ04OLMAWviAUNGFptw5qCfCzI4MgEt8THXIHUl++jbhOnU99vjjD3a5Tjo1eVPGitdwf6yh0idBGvgPqI0jyf9HTMtKE5AFpDGDW7R0wrvQ4GQRQSlSruqh/iekCx3XCqBDKPVEii603uJ9plClVkUjnzAJ/woFD7fDIIHNdtbTtmC7IXyiPgdqlIti4Mo7AAOOydWBE5+8PW++0aUXL7RCFd81fKls0aE8uM2OjFsWdaaHAArAOffWj1jp5biBTwiZ+A1li4At3I7nYNGzyyBgD0G/ls5T0/7Nl36GVmlnVgbS3XSVwbNXXsvaa/GwSIIlHZkyBYukAo/jNbmvLywKG2ohb7z213TtIEHumZY1UvQOdKG+fadHAxYJkA2AcX2+dGm3ZrWojtZ+g0q6mkLMv7TL3gycuE1rhh9u6yRryBmbeBJNd33dkEEf/UxEnYr6qH37HVrAbRogb//0y4pZA9bfWVCC6syg3avlfwmC6QXlOzl0sScUQZq+CLDSw9BKm/kpEQeLPf+CG8738gUv+X1kB1n3ZjTK/tdhvuOOmRnBdJUShYHaK/ldVk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
